# *Day_4_Data types in Python*
# *1.Numeric*

In [ ]:
#Numeric

x = 10 #integer
y = 10.5 #float
z = 10+ 5j # 10 is a real number and 5j is a imaginery number

In [1]:
x = 10
type(x)

int

In [2]:
y= 10.5
type(y)

float

In [3]:
z = 10+5j
type(z)

complex

In [5]:
isinstance(z,complex)

True

In [42]:
isinstance(10,int)

True

In [43]:
isinstance(10,float)

False

#Integer to Float
#Float to Int

In [6]:
n = float(x) #n=float

In [7]:
n

10.0

In [8]:
type(n)

float

In [9]:
n = int(n)

In [10]:
n

10

In [11]:
type(n)

int

#Int to Complex
#Float to complex
#But not possible from complex to Int/Float

In [12]:
n = complex(n) #10+0J

In [13]:
n

(10+0j)

In [14]:
type(n)

complex

In [21]:
n = int(n)

TypeError: int() argument must be a string, a bytes-like object or a real number, not 'complex'

In [22]:
n = float(n)

TypeError: float() argument must be a string or a real number, not 'complex'

In [25]:
n = complex(input('Enter your complex num : ')) #input complex

Enter your complex num :  1

In [26]:
n

(1+0j)

In [27]:
n = complex(input('Enter your complex num : '))

Enter your complex num :  1+5J

In [28]:
n

(1+5j)

In [30]:
type(n)

complex

# *2.Boolean Data Type*

In [33]:
x = True

In [40]:
y = False

In [35]:
x

True

In [41]:
y

False

# Day_4.1
# *3.Sequence data type*

In [ ]:
#lists []
can store multiple type value

In [44]:
l = [1,2,3,4,True,[1,2],'data',(1,2,3,8)]

In [45]:
l

[1, 2, 3, 4, True, [1, 2], 'data', (1, 2, 3, 8)]

In [46]:
l[0] #indexing

1

In [47]:
l[-1] #indexing_showing full tuple

(1, 2, 3, 8)

In [50]:
l[-1][2] #Showing particular value in the tuple

3

In [51]:
type(l)

list

In [52]:
isinstance(l,list)

True

In [ ]:
# Tuple()

In [57]:
t = (1,5,8,9,'Ai')
type(t) #checking data type

tuple

In [56]:
t[1] #indexing

5

In [61]:
t [0:4] #colon means to (n-1)=(4-1)=3 means 0,1,2,3

(1, 5, 8, 9)

In [60]:
#Range()

In [66]:
x = range(10) #1st case (4 situations can happen)

In [63]:
x

range(0, 10)

In [67]:
for i in x:
    print(i)

0
1
2
3
4
5
6
7
8
9

In [74]:
x = range(5,10) #2nd case
for p in x:
    print(p)

5
6
7
8
9

In [77]:
x = range(5,20,3) #3rd case_gap3
for p in x:
    print(p)

5
8
11
14
17

In [78]:
x = range(20,5,-3) #4th case_gap3
for p in x:
    print(p)

20
17
14
11
8

In [79]:
#array
import array as ar

In [84]:
a = ar.array([1,2,3,4]) #one value at a time, can't take multiple values
a

TypeError: array() argument 1 must be a unicode character, not list

In [83]:
a = ar.array('i',[1,2,3,4]) #mention integer by 'i'
a

array('i', [1, 2, 3, 4])

In [85]:
type(a)

array.array

In [86]:
#string
x='data'
type(x)

str

In [87]:
x = "data"
x

'data'

In [88]:
x = """
I love 
data science
"""
x

'\nI love \ndata science\n'

In [89]:
type(x)

str

# *4.Set types*

In [91]:
s = {1,2,3,5}
s

{1, 2, 3, 5}

# *5.Mapping type*

In [97]:
# Dictionary{}_central data structure_works as Key value & Id

In [106]:
dic = {
    'varsity':'Freie Uni',
    'dept':'Pharmacy'
}

In [107]:
dic

{'varsity': 'Freie Uni', 'dept': 'Pharmacy'}

In [108]:
type(dic)

dict

In [109]:
dic.keys()

dict_keys(['varsity', 'dept'])

In [111]:
dic.values()

dict_values(['Freie Uni', 'Pharmacy'])

# *6.Data Frame*
#Tabular form

In [112]:
#Pandas

In [116]:
import pandas as pd

In [117]:
df = pd.read_csv('Excel data for python practise.csv')

In [118]:
df.head()

,Bx PC-3,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Replica-1,Mean grey value,minus background,Caveolin/tubulin,Normalised,NaN,Replica-2,Mean grey value,minus background,Caveolin/tubulin,Normalised,NaN,Replica-3,Mean grey value,minus background,Caveolin/tubulin,Normalised
2,Ctrl,102.076,100.908,5.214883721,1,NaN,Ctrl,165.983,164.315,15.82996146,1,NaN,Ctrl,167.06,165.318,3.946478873,1
3,Caveolin-1,85.681,84.513,4.081570559,0.782677194,NaN,Caveolin-1,109.949,108.281,10.10366707,0.638262266,NaN,Caveolin-1,154.888,153.146,3.792150551,0.960894679
4,PINCH-1,96.978,95.810,4.900265957,0.939669266,NaN,PINCH-1,125.621,123.953,5.731665588,0.36207704,NaN,PINCH-1,175.741,173.999,4.333723537,1.098124094

In [120]:
df.shape #row,coloum

(39, 17)

In [122]:
df.head(39)

,Bx PC-3,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Replica-1,Mean grey value,minus background,Caveolin/tubulin,Normalised,NaN,Replica-2,Mean grey value,minus background,Caveolin/tubulin,Normalised,NaN,Replica-3,Mean grey value,minus background,Caveolin/tubulin,Normalised
2,Ctrl,102.076,100.908,5.214883721,1,NaN,Ctrl,165.983,164.315,15.82996146,1,NaN,Ctrl,167.06,165.318,3.946478873,1
3,Caveolin-1,85.681,84.513,4.081570559,0.782677194,NaN,Caveolin-1,109.949,108.281,10.10366707,0.638262266,NaN,Caveolin-1,154.888,153.146,3.792150551,0.960894679
4,PINCH-1,96.978,95.810,4.900265957,0.939669266,NaN,PINCH-1,125.621,123.953,5.731665588,0.36207704,NaN,PINCH-1,175.741,173.999,4.333723537,1.098124094
5,CAV+PIN,87.684,86.516,4.636690069,0.889126262,NaN,CAV+PIN,127.633,125.965,10.01948775,0.632944545,NaN,CAV+PIN,153.184,151.442,3.557481795,0.901431861
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Tubulin,20.518,19.350,NaN,NaN,NaN,Tubulin,12.048,10.38,NaN,NaN,NaN,Tubulin,43.632,41.89,NaN,NaN
8,Tubulin,21.874,20.706,NaN,NaN,NaN,Tubulin,12.385,10.717,NaN,NaN,NaN,Tubulin,42.127,40.385,NaN,NaN
9,Tubulin,20.72,19.552,NaN,NaN,NaN,Tubulin,23.294,21.626,NaN,NaN,NaN,Tubulin,41.892,40.15,NaN,NaN
10,Tubulin,19.827,18.659,NaN,NaN,NaN,Tubulin,14.24,12.572,NaN,NaN,NaN,Tubulin,44.312,42.57,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Background,1.168,NaN,NaN,NaN,NaN,Background,1.668,NaN,NaN,NaN,NaN,Background,1.742,NaN,NaN,NaN
13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Replica-1,Mean grey value,minus background,PINCH/tubulin,Normalised,NaN,Replica-2,Mean grey value,minus background,PINCH/tubulin,Normalised,NaN,Replica-3,Mean grey value,minus background,PINCH/tubulin,Normalised
17,Ctrl,33.392,32.196,1.040661969,1,NaN,Ctrl,17.986,16.307,0.391261577,1,NaN,Ctrl,23.749,21.919,0.327672552,1
18,Caveolin-1,20.45,19.254,0.77856854,0.748147394,NaN,Caveolin-1,14.966,13.287,0.39345573,1.005607893,NaN,Caveolin-1,16.217,14.387,0.284316825,0.867685816
19,PINCH-1,4.045,2.849,0.105323475,0.101208152,NaN,PINCH-1,8.719,7.04,0.217471889,0.555822248,NaN,PINCH-1,7.665,5.835,0.104883792,0.320087207
20,CAV+PIN,2.454,1.258,0.044627337,0.042883605,NaN,CAV+PIN,7.578,5.899,0.198827059,0.508169139,NaN,CAV+PIN,7.293,5.463,0.092394338,0.281971551
21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Tubulin,32.134,30.938,NaN,NaN,NaN,Tubulin,43.357,41.678,NaN,NaN,NaN,Tubulin,68.723,66.893,NaN,NaN
23,Tubulin,25.926,24.730,NaN,NaN,NaN,Tubulin,35.449,33.77,NaN,NaN,NaN,Tubulin,52.432,50.602,NaN,NaN
24,Tubulin,28.246,27.050,NaN,NaN,NaN,Tubulin,34.051,32.372,NaN,NaN,NaN,Tubulin,57.463,55.633,NaN,NaN
25,Tubulin,29.385,28.189,NaN,NaN,NaN,Tubulin,31.348,29.669,NaN,NaN,NaN,Tubulin,60.957,59.127,NaN,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Background,1.196,NaN,NaN,NaN,NaN,Background,1.679,NaN,NaN,NaN,NaN,Background,1.83,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39 entries, 0 to 38
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Bx PC-3      20 non-null     object
 1   Unnamed: 1   20 non-null     object
 2   Unnamed: 2   18 non-null     object
 3   Unnamed: 3   10 non-null     object
 4   Unnamed: 4   10 non-null     object
 5   Unnamed: 5   0 non-null      float64
 6   Unnamed: 6   20 non-null     object
 7   Unnamed: 7   20 non-null     object
 8   Unnamed: 8   18 non-null     object
 9   Unnamed: 9   10 non-null     object
 10  Unnamed: 10  10 non-null     object
 11  Unnamed: 11  0 non-null      float64
 12  Unnamed: 12  20 non-null     object
 13  Unnamed: 13  20 non-null     object
 14  Unnamed: 14  18 non-null     object
 15  Unnamed: 15  10 non-null     object
 16  Unnamed: 16  10 non-null     object
dtypes: float64(2), object(15)
memory usage: 5.3+ KB

# *Binary Type*

In [127]:
byte_arr = bytearray('ABCDEF', 'utf-8') #UnicodeTransformFormat

In [128]:
type(byte_arr)

bytearray

In [129]:
byte_arr

bytearray(b'ABCDEF')

In [133]:
memoryview(byte_arr) #transfer to memoryview type

In [132]:
memoryview(byte_arr) [0] #ascii code of A=65

65

In [137]:
mv = memoryview(byte_arr) #If I want to change the first value A to a, here ascii code for 'a' =97
mv[0] = 97

In [135]:
memoryview(byte_arr) [0]

97

In [138]:
byte_arr

bytearray(b'aBCDEF')